development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: tsekmark_development

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: tsekmark_development

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: tsekmark_development

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: tsekmark_production