development:
  api_key: mxud0r7e8whs
#  api_key: qojn3irfi3fc
  api_secret: bPrj85piTneCuWKq
#  api_secret: 4UzdzxBREnAb4pty
test:
  api_key: mxud0r7e8whs
  api_secret: bPrj85piTneCuWKq
staging:
  api_key: mxud0r7e8whsa
  api_secret: bPrj85piTneCuWKq
production:
#  api_key: mxud0r7e8whs
  api_key: qojn3irfi3fc
#  api_secret: bPrj85piTneCuWKq
  api_secret: 4UzdzxBREnAb4pty