development:
  app_id: 6qcPDF87wO3NHa9aBkt7zA
#  app_id: u6c5JBpoHjAEEN8VkR6Eg
  app_secret: KJA4HiWOIeRri1DZAyOi02mPrC8YfBEIxIiPNZ8XhpM
#  app_secret: pB60YO5uKdCXpBjDzjniTjfs2WfRn94GhsnLoNNeM
test:
  app_id: 6qcPDF87wO3NHa9aBkt7zA
  app_secret: KJA4HiWOIeRri1DZAyOi02mPrC8YfBEIxIiPNZ8XhpM
staging:
  app_id: 6qcPDF87wO3NHa9aBkt7zA
  app_secret: KJA4HiWOIeRri1DZAyOi02mPrC8YfBEIxIiPNZ8XhpM
production:
#  app_id: 6qcPDF87wO3NHa9aBkt7zA
  app_id: u6c5JBpoHjAEEN8VkR6Eg
#  app_secret: KJA4HiWOIeRri1DZAyOi02mPrC8YfBEIxIiPNZ8XhpM
  app_secret: pB60YO5uKdCXpBjDzjniTjfs2WfRn94GhsnLoNNeM
