development:
  app_id: dj0yJmk9SHo3VEY0dHJnQjV6JmQ9WVdrOWNuZDFPV1I0TXpJbWNHbzlOelE1TkRFek16WXkmcz1jb25zdW1lcnNlY3JldCZ4PWQw
  app_secret: 3da2aef6571a160d4b6d7cbfedfbb2f0f8238c31
test:
  app_id: dj0yJmk9SHo3VEY0dHJnQjV6JmQ9WVdrOWNuZDFPV1I0TXpJbWNHbzlOelE1TkRFek16WXkmcz1jb25zdW1lcnNlY3JldCZ4PWQw
  app_secret: 3da2aef6571a160d4b6d7cbfedfbb2f0f8238c31
staging:
  app_id: dj0yJmk9SHo3VEY0dHJnQjV6JmQ9WVdrOWNuZDFPV1I0TXpJbWNHbzlOelE1TkRFek16WXkmcz1jb25zdW1lcnNlY3JldCZ4PWQw
  app_secret: 3da2aef6571a160d4b6d7cbfedfbb2f0f8238c31
production:
  app_id: dj0yJmk9REE5TU83dU5BOXFPJmQ9WVdrOVlVTm5aVU00TkRRbWNHbzlNVEV5TURBek56STJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD1kNQ--
  app_secret: a753b359d8dec27f7d47c706bc384df10968edbb